/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'eric' at '3/5/17 5:28 PM' with Gradle 2.14.1
 *
 * @author eric, @date 3/5/17 5:28 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
